name: Update gradle
on:
  workflow_dispatch:
  schedule:
    - cron: '3 6 * * *'
permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  update-gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Update gradle
      run: .scripts/gradle.sh
    - uses: gradle/wrapper-validation-action@v1
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        title: "Update gradle"
        commit-message: "Update gradle"
        branch-suffix: timestamp
